kind: pipeline
name: default

concurrency:
  limit: 1

test_when_condition: &test_when_condition
  when:
    branch: [ master ]

prod_when_condition: &prod_when_condition
  when:
    ref:
      - refs/tags/release-*


steps:
- name: composer_auth
  image: composer
  environment:
    BACKPACK_COMPOSER_USER:
      from_secret: backpack_composer_user
    BACKPACK_COMPOSER_PASS:
      from_secret: backpack_composer_pass
  commands:
    - cd server
    - composer config http-basic.backpackforlaravel.com $BACKPACK_COMPOSER_USER $BACKPACK_COMPOSER_PASS
  <<: *test_when_condition


- name: build
  image: plugins/docker
  pull: always
  settings:
    repo: docker-registry.la.utexas.edu/lrc
    tags:
      - 'drone-${DRONE_BUILD_NUMBER}'
  <<: *test_when_condition


- name: deploy_test
  image: quay.io/honestbee/drone-kubernetes
  settings:
    kubernetes_token:
      from_secret: kubernetes_token
    kubernetes_server:
      from_secret: kubernetes_server
    namespace: lrc-test
    deployment: web
    container: web
    repo: docker-registry.la.utexas.edu/lrc
    tag: drone-${DRONE_BUILD_NUMBER}
  <<: *test_when_condition



- name: deploy_prod
  image: quay.io/honestbee/drone-kubernetes
  settings:
    kubernetes_token:
      from_secret: kubernetes_token
    kubernetes_server:
      from_secret: kubernetes_server
    namespace: lrc
    deployment: web
    container: web
    repo: docker-registry.la.utexas.edu/lrc
    tag: drone-${DRONE_BUILD_NUMBER}
  <<: *prod_when_condition

