kind: pipeline
name: default


steps:
- name: prebuild
  image: node:9
  pull: always
  commands:
    - cd server && npm rebuild && npm run production


- name: publish_test
  image: plugins/docker
  pull: always
  settings:
    repo: docker-registry.la.utexas.edu/lrc
    tags:
    - 'test'
  when:
    branch:
    - master


- name: deploy_test
  image: peloton/drone-rancher
  pull: always
  settings:
    url: https://rancher.la.utexas.edu/
    access_key:
      from_secret: rancher_access_key
    secret_key:
      from_secret: rancher_secret_key
    service: lrc-test/web
    docker_image: docker-registry.la.utexas.edu/lrc:test
    confirm: true
    timeout: 180
  when:
    branch:
    - master


- name: publish_prod
  image: plugins/docker
  pull: always
  settings:
    repo: docker-registry.la.utexas.edu/lrc
    tags:
    - 'prod'
  when:
    ref:
    - refs/tags/release-*


- name: deploy_prod
  image: peloton/drone-rancher
  pull: always
  settings:
    url: https://rancher.la.utexas.edu/
    access_key:
      from_secret: rancher_access_key
    secret_key:
      from_secret: rancher_secret_key
    service: lrc/web
    docker_image: docker-registry.la.utexas.edu/lrc:prod
    confirm: true
    timeout: 180
  when:
    ref:
    - refs/tags/release-*
