version: "3"

services:
  web:
    build:
      context: .
      args:
        BACKPACK_COMPOSER_USER: "GET_THIS_FROM_STACHE"
        BACKPACK_COMPOSER_PASS: "GET_THIS_FROM_STACHE_TOO"
    ports:
      - "80"
    volumes:
      - './server:/var/www/html'
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST:-lrc.localhost.utexas.edu}
      - APP_NAME=LRC
      - APP_ENV=local
      - APP_KEY=base64:MHLjzpUSRe5Y229TnPpokCQXW/a6l9C769NXRxRRJK8=
      - APP_DEBUG=true
      - APP_URL=${APP_URL:-https://lrc.localhost.utexas.edu}
      - LOG_CHANNEL=errorlog
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=lrc
      - DB_USERNAME=lrc
      - DB_PASSWORD=lrc
      - CACHE_DRIVER=database
      - SESSION_DRIVER=database
      - SESSION_LIFETIME=120
      - VIEW_COMPILED_PATH=/tmp/laravel
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: 'lrc'
      MYSQL_USER: 'lrc'
      MYSQL_PASSWORD: 'lrc'
      MYSQL_ROOT_PASSWORD: 'lrc'
    ports:
      - '${DB_EXPOSED_PORT:-13309}:3306'
    expose:
      - '3306'
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: